export { default as Home } from './Home'
export { default as Product } from './Product'
export { default as Collection } from './Collection'
export { default as Store } from './Store'
export { default as About } from './About'
